name: time_tracking_system1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  baseflow_plugin_template: ^2.1.2
  camera: ^0.10.5+9
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  geolocator: ^11.0.0
  get: ^4.6.6
  google_fonts: 6.1.0
  google_mlkit_face_detection: ^0.9.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  line_awesome_flutter: ^2.0.0
  local_auth: ^2.2.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/memoji/
    - assets/images/

