name: time_tracking_system
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
dependency_overrides:
  web: 0.4.2 # latest version as of now
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  responsive_builder: ^0.7.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  font_awesome_flutter: ^10.2.1
  flutter_shapes: ^0.3.0
  provider: ^6.0.4
  flutter_feather_icons: ^2.0.0+1
  tcard: ^1.3.5
  fl_chart: ^0.66.2
  flutter_slidable: ^3.0.1
  table_calendar: ^3.0.8
  glassmorphism: ^3.0.0
  firebase_database: ^10.4.6
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_pagination: ^3.1.0
  firebase_ml_vision: 0.12.0+3
  syncfusion_flutter_gauges: ^24.2.8
  flutter_localizations:
    sdk: flutter
  syncfusion_localizations: ^24.2.8
  url_launcher: ^6.2.5
  syncfusion_flutter_charts: ^24.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/memoji/
    - assets/images/



