// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbz2D1RlvmCx7Yy3g5bsm1U5Y_HdjlXrY',
    appId: '1:665929694740:web:3e0eb32f1cd2a91ce67101',
    messagingSenderId: '665929694740',
    projectId: 'timetracker-fbb10',
    authDomain: 'timetracker-fbb10.firebaseapp.com',
    storageBucket: 'timetracker-fbb10.appspot.com',
    measurementId: 'G-WSWS67XFMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArob4Qzu4DzmoRswJbUWAKIkIi-4uG-v8',
    appId: '1:665929694740:android:37f8b741648d01dbe67101',
    messagingSenderId: '665929694740',
    projectId: 'timetracker-fbb10',
    storageBucket: 'timetracker-fbb10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7e8sZYCNlVZtI-Gco6rKvPi4LQrSNkfA',
    appId: '1:665929694740:ios:9860840686027674e67101',
    messagingSenderId: '665929694740',
    projectId: 'timetracker-fbb10',
    storageBucket: 'timetracker-fbb10.appspot.com',
    iosClientId: '665929694740-bbdsqmbm4h5pbfgpsj4hhq8vt5b24n60.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackingSystem1',
  );
}
