name: timetrackingsystem
description: Use for employee attendance track

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  pie_chart: ^5.4.0
  google_nav_bar: ^5.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

   
  






